### ISSUE TITLE
course2中的问题

### ISSUE THREAD

**Issue by NotUr77** [zjhellofss/kuiperdatawhale#13]
创建张量操作时，创建3维张量时考虑了rows或者channels等于1的情况，创建2维张量时为什么没有考虑rows为1的情况。请问这是疏漏还是某种特殊考虑。

**Comment by zjhellofss** [comment]
好的，谢谢。最近有点忙，今天才看见，这确实是个问题，我等下移动到主项目的issue里了。

**Comment by sanbuphy** [comment]
其实reshape也没考虑 1,x,x这样的情况，应该自然退化

> 好的，谢谢。最近有点忙，今天才看见，这确实是个问题，我等下移动到主项目的issue里了。

**Comment by zjhellofss** [comment]
https://github.com/zjhellofss/KuiperInfer/commit/2c00a253b015ae80f02a06132e01da4f42c6cde6 已经修改
